service: nest-yale-alarm

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-1
  memorySize: 128
  timeout: 10
  logRetentionInDays: 7
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

functions:
  update:
    handler: src/handlers.update
    events:
      - schedule: rate(5 minutes)
